    !INTERFILE :=
    name of data file := test.hs
    originating system := PET
    !GENERAL DATA :=
    !GENERAL IMAGE DATA :=
    !type of data := PET 
    imagedata byte order := LITTLEENDIAN
    !PET STUDY (General) := 
    !PET data type := Emission
    applied corrections := {None}
    !number format := float
    !number of bytes per pixel := 4
    number of dimensions := 4
    matrix axis label [4] := segment
    !matrix size [4] := 1
    matrix axis label [3] := view
    !matrix size [3] := 480
    matrix axis label [2] := axial coordinate
    !matrix size [2] := {1,1 }
    matrix axis label [1] := tangential coordinate
    !matrix size [1] := 480
    minimum ring difference per segment := 0
    maximum ring difference per segment := 1
    Scanner parameters:= 
    Scanner type := PET
    Number of rings                          := 1
    Number of detectors per ring             := 960
    Inner ring diameter (cm)                 := 0.0
    Average depth of interaction (cm)        := 0
    Distance between rings (cm)              := 0.2
    Default bin size (cm)                    := 0.2
    View offset (degrees)                    := 0.0
    Maximum number of non-arc-corrected bins := 480
    Default number of arc-corrected bins     := 480
    Number of blocks per bucket in transaxial direction         := 1
    Number of blocks per bucket in axial direction              := 5
    Number of crystals per block in transaxial direction        := 20
    Number of crystals per block in axial direction             := 20
    Number of detector layers                                   := 1
    Number of crystals per singles unit in transaxial direction := 20
    Number of crystals per singles unit in axial direction      := 20
    end scanner parameters:=
    effective central bin size (cm) := 0.0
    image scaling factor[1] := 1.0
    data offset in bytes[1] := 0.0
    number of time frames := 1
    !END OF INTERFILE :=
    